name: build
on: push
jobs:
  build:
    name: build plugin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.3.25
          - 7.4.13

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: install dependencies
        run:
          sudo apt update && sudo apt install -y re2c libtool libtool-bin zlib1g-dev libcurl4-openssl-dev libxml2-dev libyaml-dev libgmp-dev libzip-dev libssl-dev libtidy-dev libxslt-dev libonig-dev libmcrypt-dev

      - name: setup path
        run: echo ~/.phpenv/bin >>$GITHUB_PATH

      - name: setup php
        run: |
          git clone https://github.com/phpenv/phpenv.git ~/.phpenv
          git clone https://github.com/php-build/php-build $(phpenv root)/plugins/php-build

          eval "$(phpenv init -)"
          phpenv install ${{ matrix.php }}
          phpenv local ${{ matrix.php }}

          git clone https://github.com/pmmp/pthreads.git
          cd pthreads
          git checkout 2bcd8b8c10395d58b8a9bc013e3a5328080c867f
          phpize

          ./configure
          make -j4
          make install

          echo "extension=pthreads.so" > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/pthreads.ini
        env:
          PHP_BUILD_CONFIGURE_OPTS: "--enable-maintainer-zts"
          PHP_BUILD_INSTALL_EXTENSION: "yaml=2.0.4"
          PHP_BUILD_EXTRA_MAKE_ARGUMENTS: "-j4"

      - name: build plugin
        run: |
          eval "$(phpenv init -)"
          composer install
          composer build

      - name: upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ matrix.php == '7.4.13' }}
        with:
          name: BigBrother.phar
          path: build/BigBrother.phar
