name: build
on: push
jobs:
  build:
    name: build plugin
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-zts
    strategy:
      matrix:
        php:
          - 7.3.25
          - 7.4.13

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: install dependencies
        run: |
          apt update
          apt-get install -y git curl libyaml-dev

      - name: install yaml extension
        run: |
          pecl install channel://pecl.php.net/yaml-2.0.4
          docker-php-ext-enable yaml

      - name: install sockets extension
        run: docker-php-ext-install sockets

      - name: install pthreads extension
        run: |
          git clone https://github.com/pmmp/pthreads.git /usr/local/src/pthreads
          cd /usr/local/src/pthreads
          git checkout 2bcd8b8c10395d58b8a9bc013e3a5328080c867f
          phpize
          ./configure
          make
          make install
          docker-php-ext-enable pthreads

      - name: install composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: build
        run: |
          composer install
          composer build

      - name: upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ matrix.php == '7.4.13' }}
        with:
          name: BigBrother.phar
          path: build/BigBrother.phar
